# Generated by Django 6.0.7 on 2026-07-22 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('template_version', models.IntegerField(blank=True, null=True)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('args_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('backend', models.CharField(blank=True, max_length=50)),
                ('owner', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('vm_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('raw_yaml', models.TextField(help_text='the template.yaml body; source of truth')),
                ('params', models.CharField(blank=True, max_length=500)),
                ('version', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(help_text='principal id', max_length=200)),
                ('role', models.CharField(default='user', max_length=20)),
                ('quota', models.IntegerField(blank=True, help_text='max concurrent envs', null=True)),
                ('max_ttl', models.CharField(blank=True, max_length=10)),
                ('backend', models.CharField(blank=True, max_length=50)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='display only', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('created', 'created'), ('status', 'status change'), ('exec', 'exec'), ('shared', 'shared'), ('unshared', 'unshared'), ('exposed', 'exposed'), ('unexposed', 'unexposed'), ('ssh-cert', 'ssh cert issued'), ('destroyed', 'destroyed'), ('error', 'error')], max_length=20)),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='environments.environment')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddField(
            model_name='environment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='environments.template'),
        ),
        migrations.CreateModel(
            name='EnvironmentGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(db_index=True, help_text='the principal id being granted access', max_length=200)),
                ('granted_by', models.CharField(blank=True, max_length=200)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='environments.environment')),
            ],
            options={
                'ordering': ['principal'],
                'unique_together': {('environment', 'principal')},
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=63)),
                ('port', models.IntegerField()),
                ('access', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='environments.environment')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('environment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('raw_yaml', models.TextField()),
                ('params', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='environments.template')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('template', 'version')},
            },
        ),
    ]
