# Generated by Django 6.0.7 on 2026-07-30 16:16

from django.db import migrations, models


def release_dead_labels(apps, schema_editor):
    """Remove capabilities left by deployments predating teardown cleanup."""
    Exposure = apps.get_model("environments", "Exposure")
    Exposure.objects.filter(environment__status__in=["destroyed", "error"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_viewermagictoken'),
    ]

    operations = [
        migrations.RunPython(release_dead_labels, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='exposure',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
