# Generated by Django 6.0.7 on 2026-07-30 16:26

import django.db.models.deletion
from django.db import migrations, models


def populate_leases(apps, schema_editor):
    Environment = apps.get_model('environments', 'Environment')
    NamespaceLease = apps.get_model('environments', 'NamespaceLease')
    live = Environment.objects.exclude(status__in=['destroyed', 'error'])
    for environment in live.iterator():
        NamespaceLease.objects.create(name=environment.pk, environment=environment)
    Exposure = apps.get_model('environments', 'Exposure')
    exposures = Exposure.objects.exclude(
        environment__status__in=['destroyed', 'error'])
    for exposure in exposures.iterator():
        lease, created = NamespaceLease.objects.get_or_create(
            name=exposure.name, defaults={'environment_id': exposure.environment_id})
        if not created and lease.environment_id != exposure.environment_id:
            raise RuntimeError(
                f"namespace label {exposure.name!r} has conflicting owners")


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_alter_exposure_unique_together_alter_exposure_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerQuotaLock',
            fields=[
                ('owner', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateNameLock',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NamespaceLease',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace_leases', to='environments.environment')),
            ],
        ),
        migrations.RunPython(populate_leases, migrations.RunPython.noop),
    ]
